fn main() {
    println!("Rust Learning コース一覧");
    println!();
    println!("Chapter 1: introduction コース");
    println!();
    println!("  01  enum とデータを持つバリアント");
    println!("  02  match とパターンマッチ");
    println!("  03  Result とエラーの伝播");
    println!("  04  独自エラー型");
    println!("  05  イテレータ");
    println!();
    println!("Chapter 2: ownership コース");
    println!();
    println!("  01  ムーブと所有権の移動");
    println!("  02  Copy と Clone");
    println!("  03  共有借用とスライス");
    println!("  04  可変借用と再借用");
    println!("  05  荷物引き渡しチャレンジ");
    println!();
    println!("Chapter 3: data-modeling コース");
    println!();
    println!("  01  入れ子の構造体と構造体更新記法");
    println!("  02  関連関数とメソッド");
    println!("  03  newtype と単位の型安全性");
    println!("  04  コンストラクタと不変条件");
    println!("  05  型安全な配送ミッション");
    println!();
    println!("Chapter 4: collections コース");
    println!();
    println!("  01  Vec と荷物棚");
    println!("  02  VecDeque と配送待ちキュー");
    println!("  03  HashMap と部品在庫");
    println!("  04  HashSet とロボット能力");
    println!("  05  UTF-8 と日本語ログ解析");
    println!();
    println!("Chapter 5: generics-traits コース");
    println!();
    println!("  01  Cargo<T> とジェネリック型");
    println!("  02  独自トレイトとデフォルトメソッド");
    println!("  03  impl Trait とトレイト境界");
    println!("  04  From / Into と TryFrom / TryInto");
    println!("  05  交換可能な配送ポリシー");
    println!();
    println!("Chapter 6: lifetimes コース");
    println!();
    println!("  01  複数入力と明示的なライフタイム");
    println!("  02  ゼロコピーのログ解析");
    println!("  03  借用する MissionCatalog");
    println!("  04  独立した2つの借用");
    println!("  05  Cow による借用または所有");
    println!();
    println!("Chapter 6 の始め方: cargo test --example lifetimes_01_lifetime_relations");
    println!("詳しい説明: lifetimes/README.md");
}
