fn main() {
    println!("Rust Learning コース一覧");
    println!();
    println!("Chapter 1: introduction コース");
    println!();
    println!("  01  enum とデータを持つバリアント");
    println!("  02  match とパターンマッチ");
    println!("  03  Result とエラーの伝播");
    println!("  04  独自エラー型");
    println!("  05  イテレータ");
    println!();
    println!("Chapter 2: ownership コース");
    println!();
    println!("  01  ムーブと所有権の移動");
    println!("  02  Copy と Clone");
    println!("  03  共有借用とスライス");
    println!("  04  可変借用と再借用");
    println!("  05  荷物引き渡しチャレンジ");
    println!();
    println!("Chapter 3: data-modeling コース");
    println!();
    println!("  01  入れ子の構造体と構造体更新記法");
    println!("  02  関連関数とメソッド");
    println!("  03  newtype と単位の型安全性");
    println!("  04  コンストラクタと不変条件");
    println!("  05  型安全な配送ミッション");
    println!();
    println!("Chapter 4: collections コース");
    println!();
    println!("  01  Vec と荷物棚");
    println!("  02  VecDeque と配送待ちキュー");
    println!("  03  HashMap と部品在庫");
    println!("  04  HashSet とロボット能力");
    println!("  05  UTF-8 と日本語ログ解析");
    println!();
    println!("Chapter 5: generics-traits コース");
    println!();
    println!("  01  Cargo<T> とジェネリック型");
    println!("  02  独自トレイトとデフォルトメソッド");
    println!("  03  impl Trait とトレイト境界");
    println!("  04  From / Into と TryFrom / TryInto");
    println!("  05  交換可能な配送ポリシー");
    println!();
    println!("Chapter 6: lifetimes コース");
    println!();
    println!("  01  複数入力と明示的なライフタイム");
    println!("  02  ゼロコピーのログ解析");
    println!("  03  借用する MissionCatalog");
    println!("  04  独立した2つの借用");
    println!("  05  Cow による借用または所有");
    println!();
    println!("Chapter 7: closures-iterators コース");
    println!();
    println!("  01  クロージャのキャプチャと move");
    println!("  02  Fn / FnMut / FnOnce");
    println!("  03  遅延する配送パイプライン");
    println!("  04  scan と try_fold");
    println!("  05  独自 Iterator による公平配送");
    println!();
    println!("Chapter 8: smart-pointers コース");
    println!();
    println!("  01  Box と再帰的な配送経路");
    println!("  02  Deref / DerefMut と Drop");
    println!("  03  Rc によるキャンパスマップ共有");
    println!("  04  RefCell と内部可変性");
    println!("  05  Weak による循環しない所有関係");
    println!();
    println!("Chapter 9: concurrency コース");
    println!();
    println!("  01  spawn・move・JoinHandle");
    println!("  02  scope と借用データの並列処理");
    println!("  03  mpsc チャネルと所有権の移送");
    println!("  04  Arc<Mutex<T>> と共有台帳");
    println!("  05  Send・Sync と固定ワーカー");
    println!();
    println!("Chapter 10: async-rust コース");
    println!();
    println!("  01  async・await と task");
    println!("  02  Future・Poll・Waker・Pin");
    println!("  03  小さな executor");
    println!("  04  backpressure・timeout・キャンセル");
    println!("  05  select! と graceful shutdown");
    println!();
    println!("Chapter 11: unsafe-rust コース");
    println!();
    println!("  01  raw pointer と安全な slice view");
    println!("  02  UnsafeCell と aliasing");
    println!("  03  strict provenance と offset handle");
    println!("  04  MaybeUninit による固定長 buffer");
    println!("  05  部分初期化と panic safety");
    println!();
    println!("Chapter 12: advanced-traits コース");
    println!();
    println!("  01  関連型による型の契約");
    println!("  02  blanket impl・coherence・newtype");
    println!("  03  dyn 互換性と動的 dispatch");
    println!("  04  clone 可能な trait object");
    println!("  05  Any と typed registry");
    println!("  06  GAT と lending view");
    println!("  07  HRTB と任意の lifetime の callback");
    println!("  08  RPITIT と opaque iterator");
    println!();
    println!("Chapter 12 の始め方: cargo test --example advanced_traits_01_associated_types");
    println!("詳しい説明: advanced-traits/README.md");
    println!();
    println!("Chapter 13: macro-systems コース");
    println!();
    println!("  01  式を返す macro_rules!");
    println!("  02  項目生成と反復");
    println!("  03  TT muncher で小さなDSLを読む");
    println!("  04  hygiene と $crate");
    println!("  05  macro-generated impl");
    println!();
    println!("Chapter 13 の始め方: cargo test --example macro_systems_01_expression_macros");
    println!("詳しい説明: macro-systems/README.md");
}
